### Добавление задания 1му пользователю

POST localhost:8080/api/users/1/tasks
Content-Type: application/json

{
  "description" : "Сходить в магазин за покупками",
  "title" : "Задание от жены",
  "startDate": "2025-05-10",
  "finishDate": "2025-08-11"
}


### Добавление 2го задания 1му пользователю

POST localhost:8080/api/users/1/tasks
Content-Type: application/json

{
  "description" : "Вынести мусор",
  "title" : "Задание от жены",
  "startDate": "2020-09-10",
  "finishDate": "2022-09-11"
}


### Добавление 1го задания 2му пользователю

POST localhost:8080/api/users/2/tasks
Content-Type: application/json

{
  "description" : "Помыть посуду",
  "title" : "Задание от жены",
  "startDate": "2022-10-10",
  "finishDate": "2021-10-11"
}


### Получение всех заданий 1го пользователя

GET localhost:8080/api/users/1/tasks

### Получение всех заданий 2го пользователя

GET localhost:8080/api/users/2/tasks

### Получение всех заданий по дате

GET localhost:8080/api/tasks?year=2023&month=08