### Добавление Марселя

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "sidikov.marsel@gmail.com",
  "password": "qwerty007"
}

### Добавление Алишера

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "alisher@gmail.com",
  "password": "qwerty008"
}


### Получение всех пользователей

GET localhost:8080/api/users



### Добавление события 1
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "email": "alisher@gmail.com",
  "event": "День рождения"
}

### Добавление события 2
POST http://localhost:8080/api/events
Content-Type: application/json

{
"email": "alisher@gmail.com",
"event": "Покупки"
}



### Получение событий
GET http://localhost:8080/api/events/email







